env:
  global:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
  - CC_TEST_REPORTER_ID=3061299ce65bc5627ebbf42e64717c04e393adaa72c1abbc0ea46300d2c2fdb5

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
- gem update --system
- gem install bundler

install:
- bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

language: ruby
sudo: false
rvm:
  - ruby-2.1.10
  - ruby-2.2.10
  - ruby-2.3.7
  - ruby-2.4.4
  - ruby-2.5.1
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
matrix:
  exclude:
    - rvm: ruby-2.1.10
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: ruby-2.1.10
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: ruby-2.1.10
      gemfile: gemfiles/rails_5_2.gemfile
