sqlite:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
mysql:
  adapter: mysql2
  database: activerecord_transactionable_test
  username: foss
  encoding: utf8
postgresql:
  adapter: postgresql
  database: activerecord_transactionable_test
  username: postgres
